services:
  client:
    container_name: client
    environment:
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"

  cigniter:
    container_name: app
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend:/var/www/html
      # - ./backend/php.ini:/usr/local/etc/php/
    ports:
      - "8080:80"

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  my-beauty-network:
    external: true
