FROM php:8.2-apache
WORKDIR /var/www/html

COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

#Mod rewrite
RUN a2enmod  rewrite

# Linux Library
RUN apt-get update -y && apt-get install -y \
  libpq-dev\
  libicu-dev \
  libmariadb-dev \
  postgresql\
  unzip zip \
  zlib1g-dev \
  libpng-dev \
  libjpeg-dev \
  libfreetype6-dev \
  libjpeg62-turbo-dev \
  libpng-dev \
  libzip-dev 

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# PHP Extension
RUN docker-php-ext-install gettext intl mysqli pdo pdo_mysql gd zip pgsql pdo_pgsql 

RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg \
  && docker-php-ext-install -j$(nproc) gd